### ISSUE TITLE
Incorrect requirement listed

### ISSUE THREAD

**Issue by jsumners** [boneskull/midnight-smoker#233]
https://github.com/boneskull/midnight-smoker/blob/1beeec26fa716e7bec30602d00b19c7c0e5bf480/README.md?plain=1#L48

This is incorrect. It seems to me that `midnight-smoker` does not work with Node v14 because it requires `npm@7` starting in https://github.com/boneskull/midnight-smoker/compare/v1.1.1...v1.2.1

The version of npm that ships with Node 14 is "6.14.18". Node 16 ships with npm "8.19.4".

**Comment by boneskull** [comment]
Well, it's right and it's wrong.  We need Node.js v14.17.0 or greater.  But the version of `npm` is not locked to the Node.js version (barring anything `npm` no longer supports, like node `<v14.17.0`).  It will run fine with a newer version of npm under Node.js v14.17.x.  

That said I'm probably going to drop support for Node.js v14.x soonish.

**Comment by boneskull** [comment]
Also, unsure what version of `README.md` you're quoting from, since it's updated in the current `main` branch.

**Comment by jsumners** [comment]
I was probably viewing an old tag tree because I was finding where the npm requirement was added. 

In my view, the npm version should be tied to the Node version. The two ship together to form one LTS bundle. 

I agree that 14 should be dropped soon. But it was effectively dropped in a minor/patch release with the npm engine requirement.
